version: "3.8"

services:
  mikrotik-tools:
    build: .
    container_name: mikrotik-tools
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
